# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://www.ferpecto.com"
baseurl: ""

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Rafa González

# Short description of your site
description: Pagina web personal de Rafa González, el Ferpecto.

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar.jpg"

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
# --- Misc --- #

# Output options (more information on Jekyll's site)
timezone: "America/Bogota"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - CNAME

gems:
  - jekyll-paginate
